-- ============================================================================
-- Database Initialization Script for analysis_ollama
-- ============================================================================
-- This script creates the database schema for the RSS article analysis system
-- Character Set: utf8mb4 with utf8mb4_unicode_ci collation
-- Database: analysis_ollama
-- ============================================================================

-- Create database if not exists
CREATE DATABASE IF NOT EXISTS `analysis_ollama` 
  DEFAULT CHARACTER SET utf8mb4 
  COLLATE utf8mb4_unicode_ci;

USE `analysis_ollama`;

-- ============================================================================
-- Table: analysis_articles
-- Purpose: Store article metadata fetched from wewe-rss
-- Note: Renamed from 'articles' to avoid conflict with wewe-rss database
-- ============================================================================
CREATE TABLE IF NOT EXISTS `analysis_articles` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `title` VARCHAR(512) NOT NULL COMMENT 'Article title',
  `url` VARCHAR(1024) NOT NULL COMMENT 'Article URL',
  `guid` VARCHAR(512) NOT NULL COMMENT 'Global unique identifier from RSS feed',
  `feed_id` VARCHAR(100) NULL COMMENT 'Source feed ID for multi-feed extension',
  `published_at` DATETIME NULL COMMENT 'Publication timestamp',
  `fetched_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fetch timestamp',
  `status` VARCHAR(50) NOT NULL DEFAULT 'pending' COMMENT 'Processing status: pending, processed, error',
  `summary` TEXT NULL COMMENT 'Article summary generated by LLM',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_guid` (`guid`),
  INDEX `idx_status` (`status`),
  INDEX `idx_fetched_at` (`fetched_at`),
  INDEX `idx_feed_id` (`feed_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Stores article metadata from wewe-rss feeds (analysis system)';

-- ============================================================================
-- Table: analysis_extracted_projects
-- Purpose: Store structured project information extracted from articles
-- ============================================================================
CREATE TABLE IF NOT EXISTS `analysis_extracted_projects` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `article_id` INT NOT NULL COMMENT 'Foreign key to analysis_articles table',
  `company_name` VARCHAR(255) NULL COMMENT 'Company name',
  `province` VARCHAR(100) NULL COMMENT 'Province',
  `city` VARCHAR(100) NULL COMMENT 'City',
  `client_type` VARCHAR(100) NULL COMMENT 'Client type',
  `application_scene` VARCHAR(100) NULL COMMENT 'Application scenario',
  `project_name` VARCHAR(255) NULL COMMENT 'Project name',
  `project_stage` VARCHAR(100) NULL COMMENT 'Project stage',
  `raw_json` JSON NULL COMMENT 'Raw JSON data returned by LLM',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation timestamp',
  PRIMARY KEY (`id`),
  INDEX `idx_article_id` (`article_id`),
  INDEX `idx_company_name` (`company_name`),
  INDEX `idx_location` (`province`, `city`),
  INDEX `idx_created_at` (`created_at`),
  CONSTRAINT `fk_analysis_article` FOREIGN KEY (`article_id`) 
    REFERENCES `analysis_articles` (`id`) 
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Stores structured project information extracted from articles';

-- ============================================================================
-- Table: feed_configs (FUTURE EXTENSION)
-- Purpose: Configuration for multiple RSS feeds with different webhooks
-- Status: Not implemented in current MVP, reserved for future multi-feed support
-- ============================================================================
-- FUTURE EXTENSION: Uncomment this table when implementing multi-feed support
-- This table will enable:
-- - Multiple WeChat official accounts monitoring
-- - Different webhook URLs per feed
-- - Customizable polling intervals per feed
-- - Feed-level enable/disable control
-- ============================================================================
/*
CREATE TABLE IF NOT EXISTS `feed_configs` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `feed_id` VARCHAR(100) NOT NULL COMMENT 'Feed ID from WeWe-RSS',
  `feed_name` VARCHAR(255) NOT NULL COMMENT 'WeChat official account name',
  `webhook_url` VARCHAR(1024) NOT NULL COMMENT 'WeCom webhook URL for notifications',
  `poll_interval_minutes` INT NOT NULL DEFAULT 60 COMMENT 'Polling interval in minutes',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Whether this feed is enabled',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation timestamp',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_feed_id` (`feed_id`),
  INDEX `idx_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Configuration for multiple RSS feeds (future extension)';
*/

-- ============================================================================
-- End of initialization script
-- ============================================================================
