version: '3.8'

services:
  analysis-ollama:
    image: lepure/analysis-ollama:0.0.1
    container_name: analysis-ollama
    environment:
      TZ: 'Asia/Shanghai'
    restart: unless-stopped
    # 指定环境
    env_file:
      - .env.pre
    networks:
      - lepure-business-opportunity_default
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  lepure-business-opportunity_default:
    external: true
